apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: frontend
    newName: 605238922112.dkr.ecr.us-east-1.amazonaws.com/mp-frontend
    newTag: latest