name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd starter/frontend
          npx prettier --write . || true
          npm run lint -- --fix || true

      - name: Run tests
        run: |
          cd starter/frontend
          npm run test -- --passWithNoTests --watchAll=false

  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Frontend Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mp-frontend
          IMAGE_TAG: latest
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="http://a594264b4f4a44b7994182d6a887f575-829481107.us-east-1.elb.amazonaws.com:5000" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG starter/frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1

          kubectl get pods | grep Terminating | awk '{print $1}' | xargs -r kubectl delete pod --force --grace-period=0 || true

          kubectl apply -k starter/frontend/k8s/

          kubectl rollout restart deployment/frontend
          kubectl rollout status deployment/frontend --timeout=60s || true

          echo "==================== PODS & SERVICES ===================="
          kubectl get pods -o wide
          kubectl get svc frontend